apiVersion: v1
kind: Service
metadata:
  name: authen-service-db-service
  namespace: dev
  labels:
    app: authen-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: authen-service
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authen-service-db-config
  namespace: dev
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  MYSQL_DATABASE: AuthenServiceDB
  MYSQL_USER: authen-manager
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: authen-service-sc
  namespace: dev
provisioner: k8s.io/hostpath
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authen-service-pv-volume
  namespace: dev
  labels:
    type: local
spec:
  storageClassName: authen-service-sc
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/authen-sql-init"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authen-service-pv-claim
  namespace: dev
spec:
  storageClassName: authen-service-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: authen-service-db-sc
  namespace: dev
provisioner: k8s.io/hostpath
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authen-service-db-pv-volume
  namespace: dev
  labels:
    type: local
spec:
  storageClassName: authen-service-db-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/authen-service-storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authen-service-db-pv-claim
  namespace: dev
spec:
  storageClassName: authen-service-db-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authen-service-db-deployment
  namespace: dev
  labels:
    app: authen-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authen-service
  template:
    metadata:
      labels:
        app: authen-service
    spec:
      containers:
        - name: authen-service
          image: mysql:latest
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authen-service-db-password
                  key: MYSQL_PASSWORD
          envFrom:
            - configMapRef:
                name: authen-service-db-config
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: authen-service-persistent-storage
              mountPath: "/docker-entrypoint-initdb.d"
            - name: authen-service-db-persistent-storage
              mountPath: "/var/lib/mysql"
      volumes:
        - name: authen-service-persistent-storage
          persistentVolumeClaim:
            claimName: authen-service-pv-claim
        - name: authen-service-db-persistent-storage
          persistentVolumeClaim:
            claimName: authen-service-db-pv-claim