apiVersion: v1
kind: Secret
metadata:
  name: authen-service-db-password
  namespace: dev
type: Opaque
data:
  MYSQL_PASSWORD: I-not-gonna-show-it-here
---
apiVersion: v1
kind: Secret
metadata:
  name: authen-totp-secret-key
  namespace: dev
type: Opaque
data:
  MYSQL_PASSWORD: I-not-gonna-show-it-here