version: "3.6"
services:
    db:
        build: ./db
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
        restart: always
        expose:
            - 3306
        environment:
            # These password and stuff is not neccesarry too secret
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=myDB
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_password

    app:
        build: ./app
        volumes:
            - ./app:/var/www/html
        ports:
            - "2000:2000"
        restart: always
        depends_on:
            - db
        

  