apiVersion: v1
kind: Secret
metadata:
  name: authorization-db-password
  namespace: dev
type: Opaque
data:
  MYSQL_PASSWORD: ZWI1MTk4NzQyYjk0NDNlMWI5ZjBiNTZiNDI2ZjEzMWQ4MjFhMmQ4NTI0MmFmMWU2MjdlNDYyZDk4NWYzY2RkMw==
---
apiVersion: v1
kind: Secret
metadata:
  name: authorization-crypto-key
  namespace: dev
type: Opaque
data:
  CRYPTO_KEY: YTk0MTc1YTA5ZWU2YWEzZTVhMjJmYjlkMjVkOThiMGE3MWZlMmU5OGEyNjAwYTI0YzAzNjY2NTUwNzRlM2E2Mg==
---
apiVersion: v1
kind: Secret
metadata:
  name: authorization-sign-key
  namespace: dev
type: Opaque
data:
  SIGN_KEY: OTViMWM2MzRmMDUwN2U4NTc2YmEwZWFmZWEyNmRjMGQ1M2U3YTZkNzgxYjRmMjc1Y2MwMjI3MjQxMzU2NmYzZg==
