apiVersion: v1
kind: Secret
metadata:
  name: session-management-db-password
  namespace: dev
type: Opaque
data:
  MYSQL_PASSWORD: ZWI1MTk4NzQyYjk0NDNlMWI5ZjBiNTZiNDI2ZjEzMWQ4MjFhMmQ4NTI0MmFmMWU2MjdlNDYyZDk4NWYzY2RkMw==