apiVersion: v1
kind: Service
metadata:
  name: session-management-service
  namespace: dev
  labels:
    app: session-management
spec:
  ports:
    - port: 8008
      targetPort: 80
  selector:
    app: session-management
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: session-management-db-config
  namespace: dev
data:
  AUTHOR_MYSQL_DATABASE: AuthorizationDB
  AUTHOR_MYSQL_USER: authorization-manager
  AUTHEN_MYSQL_DATABASE: AuthenServiceDB
  AUTHEN_MYSQL_USER: authen-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-management-deployment
  namespace: dev
  labels:
    app: session-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-management
  template:
    metadata:
      labels:
        app: session-management
    spec:
      containers:
      - image: suppi147/session-management
        name: session-management
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: session-management-db-password
                key: MYSQL_PASSWORD
        envFrom:
          - configMapRef:
              name: session-management-db-config        
        ports:
        - containerPort: 80