apiVersion: v1
kind: Service
metadata:
  name: session-management-service
  namespace: dev
  labels:
    app: session-management
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: session-management
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-management-deployment
  namespace: dev
  labels:
    app: session-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-management
  template:
    metadata:
      labels:
        app: session-management
    spec:
      containers:
      - image: suppi147/session-management
        name: session-management
        ports:
        - containerPort: 80