FROM python:3.8-slim
WORKDIR /app
COPY . /app
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 80
ENV FLASK_DEBUG=1
CMD ["flask", "run", "--host=0.0.0.0", "--port=80"]