apiVersion: v1
kind: Service
metadata:
  name: quote-service
  namespace: dev
  labels:
    app: quote-service
spec:
  ports:
    - port: 8008
      targetPort: 80
  selector:
    app: quote-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-service-deployment
  namespace: dev
  labels:
    app: quote-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-service
  template:
    metadata:
      labels:
        app: quote-service
    spec:
      containers:
      - image: suppi147/quote-service
        name: quote-service
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: quote-service-db-password
                key: MYSQL_PASSWORD
        envFrom:
          - configMapRef:
              name: quote-service-db-config       
        ports:
        - containerPort: 80